-- CREATE TABLE RulesUser (
--                            id serial PRIMARY KEY,
--                            name varchar(255) NOT NULL);
--
-- insert into rulesuser
-- values
-- (1, 'Add'),
-- (2, 'Edit'),
-- (3, 'Delete'),
-- (4, 'Read');
--
-- CREATE TABLE RoleUsers (
--                            id serial PRIMARY KEY REFERENCES RulesUser(id),
--                            name varchar(255) NOT NULL);
--
-- insert into roleusers
-- values
-- (1, 'Admin'),
-- (2, 'User');
--
-- CREATE TABLE Role_Rules (
--                             id serial PRIMARY KEY,
--                             role_id int references RoleUsers(id),
--                             rule_id int references RulesUser(id));
--
-- insert into Role_Rules
-- values
-- (1, 1, 1),
-- (2, 2, 2);
--
-- CREATE TABLE Users (
--                        id serial PRIMARY KEY,
--                        name varchar(255),
--                        role_id int REFERENCES RoleUsers(id));
--
-- insert into users
-- values
-- (1, 'Ivan', 1),
-- (2, 'Serg', 2),
-- (3, 'Petr', 3);
--
-- create table item_status (
--                              id serial primary key,
--                              name varchar(255));
--
-- insert into item_status
-- values
-- (1, 'Red'),
-- (2, 'Yellow'),
-- (3, 'Green');
--
--
-- create table Item_category (
--                                id serial primary key,
--                                name varchar(255));
--
-- insert into item_category
-- values
-- (1, 'New'),
-- (2, 'Worked'),
-- (3, 'Glossed');
--
-- CREATE Table items (
--                        id serial primary key,
--                        name varchar(255),
--                        iser_id int references users(id),
--                        status_id int references item_status(id),
--                        category_id int references item_category(id));
--
-- insert into items
-- values
-- (1, 'Task1', 1, 1, 2),
-- (2, 'Task2', 2, 1, 3),
-- (3, 'Task3', 3, 3, 3);
--
-- create table item_files (
--                             id serial primary key,
--                             name varchar (255),
--                             item_id int references items(id),
--                             files bytea);
--
-- insert into item_files
-- values
-- (1, 'Doc', 1, 'log.txt'),
-- (2, 'Picture', 1, 'picture.jpg');
--
--
-- create table item_comments (
--                                id serial primary key,
--                                name varchar(255),
--                                item_id int references items(id));
--
-- insert into item_comments
-- values
-- (1, 'Add', 1),
-- (2, 'Edit', 1),
-- (3, 'End', 1);
--
--
--
--
--
--
--
